### ISSUE TITLE
Feedback moves up/down arrows in numericInput

### ISSUE THREAD

**Issue by hadley** [merlinoa/shinyFeedback#21]
This is a weird one!

Run this app:

```R
library(shiny)

ui <- fluidPage(
  shinyFeedback::useShinyFeedback(),
  numericInput("n", "n", value = 10)
)
server <- function(input, output, session) {
  observeEvent(input$n,
    shinyFeedback::feedback(
      "n", 
      input$n %% 2 != 0,
      text = "Please select an even number"
    )  
  )
}

shinyApp(ui, server)
```

Then press the down button; the up and down buttons move to the left

**Comment by hadley** [comment]
Oh, I see the problem more clearly with `feedbackWarning()` — the icon is inserted to the left of the controls. Perhaps for numeric inputs it should be inserted to the right?

**Comment by merlinoa** [comment]
Thanks @hadley!   The icon is now inserted to the left of the up/down arrows for `numericInput()`.

This issue was caused because shinyFeedback adds the Bootstrap "has-feedback" class to the `numericInput`, and the "has-feedback" class adds padding in the right of the numericInput.  To remove this padding, I simply overwrote the padding-right css for the bootstrap ".has-feedback .form-control".  This works, but it does not seem like a good solution.  Perhaps a better solution would be to supply all css used by shinyFeedback with shinyFeedback, and use shinyFeedback css classes rather than use the bootstrap 3 classes.  I have added supplying all shinyFeedback css with shinyFeedback to a new todo list for the next release #22.  Please feel free to make requests or suggestions!  Thanks!
