### ISSUE TITLE
Vignette has typo

### ISSUE THREAD

**Issue by jhk0530** [merlinoa/shinyFeedback#28]
I love this package, thanks for your effort.

![image](https://user-images.githubusercontent.com/6457691/80344873-38ab0400-88a3-11ea-8538-bd7ac25ccd75.png)

There are duplicated `shiny::selectInput()` term in available input functions 

---

In addition, it's not related with technical issue, 
but I believe decorating shinyFeedBack like manual or examples without installing package could be possible. 

Thanks.

**Comment by merlinoa** [comment]
Thanks @jhk0530! The duplicate selectInput has been removed from the vignette d5ef81da60501e9fb642c9bdafa3b9785c98f2f5

Yes you can certainly add feedback styling to inputs directly with css.  shinyFeedback exists so that you don't have to style the feedback directly with css and so that you can show/hide feedback based on logic in your shiny server code rather than in JS on the frontend.

**Comment by jhk0530** [comment]
I mean "documentation" like `readme`, or `vignette` in github repository page itself, but nevermind.

Thanks.
