### ISSUE TITLE
shinyFeedback v0.2.0 on shinyapps.io: seriously degraded performance

### ISSUE THREAD

**Issue by PuzzledFace** [merlinoa/shinyFeedback#33]
I had an issue with shinyFeedback after upgrading from v0.1.0 to v0.2.0 but only on shinyapps.io.

I upgraded shinyapps from v0.1.0 to v0.2.0 on my local test machine, changing all `feedbackXXXX(condition=YYYY, ...)` calls to `feedbackXXXX(show=YYYY, ...)`.  There were no issues running the new code on my local test machine.

I published to shinyapps.io.  Rather than taking less than two seconds to load (as previously), the app now took roughly five minutes to display the main GUI.  Responding to button clicks also took minutes rather than being instant.

Reverting to v0.1.0 solved the issue.  There were no error messages or other indications of what might be going wrong in the app log files.

I'm sorry I can't provide more information at the moment.  Feel free to contact me directly if you think I might be able to help.  Thank you for a really useful package.

**Comment by merlinoa** [comment]
hmm... We haven't noticed any issues with shinyapps.io, and I don't see any reason that there should be any performance issues.  This demo app is running on shinyapps.io with shinyFeedback 0.2.0: https://tychobra.shinyapps.io/supported_inputs_app/ without issues.  We have also deployed to non shinyapps.io servers without issue.  

If you have a minute, could you possibly redeploy one more time to shinyapps.io with shinyFeedback 0.2.0 just to confirm that your issue was not just a one off networking/shinyapps.io container issue.  Thanks for reporting the issue.  I hope we can get to the bottom of it!

**Comment by PuzzledFace** [comment]
I reverted and redeployed several times in an effort to identify the source of the problem before posting here, so I'm confident it's not a temporary network/container issue.  I've contacted you separately with links to a reprex on shinyapps.io and its source code on GitHub.

**Comment by PuzzledFace** [comment]
After further investigation, Andy discovered that the cause of the degraded performance was that my `inputId`s in calls to `feedbackXXXX` inside modules were still wrapped in `ns` calls.  This was required in v0.1.0 but not in v0.2.0.  Removing the `ns` calls fixed the issue.

Thanks for the prompt and effective dialogue, Andy.
